backend:
  name: github
  repo: jamesgrubb/plastic

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - label: "Image"
        default: "/assets/Brakspear-s-01.jpg"
        name: "thumbnail"
        widget: "image"
